export const AppTheme = {
  colorPrimary: '#1A2D4E',
  backgroundGradientHome: [
    '#E5ECFF',
    '#E5ECFF',
    '#E5ECFF',
    '#E5ECFF',
    '#E5ECFF',
    '#C2D2FF',
    '#C2D2FF',
    '#C2D2FF',
    '#99B4FF',
    '#99B4FF',
  ],
  titleStyles: {
    color: '#1A2D4E',
    fontFamily: 'SawtonCircular-Thin',
    letterSpacing: 1,
  },
  backgroundFoodDetails: '#E5ECFF',
  alarmCardColors: 'white',
  topBarColor: '#E5ECFF',
  backgroundBaseColor: '#E5ECFF',
  bottomBarColor: 'white',
};
