import { Food } from "./User.model";

export const foods: Food[] = [
    {
        id: '12j3123',
        key: 0,
        name: 'Hamburguer',
        description: "O hambúrguer (do inglês hamburger), também conhecido como hamburgo, hamburguesa ou sanduíche de carne, é um preparado de carne temperada (principalmente de carne bovina, ocasionalmente de frango moído, carne suína moída, com misturas de carnes ou até \"vegetarianos\") e moldada em formato circular.",
        price: 'R$ 20,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            "https://exame.com/wp-content/uploads/2020/05/mafe-studio-LV2p9Utbkbw-unsplash-1.jpg",
            "https://img.itdg.com.br/tdg/images/blog/uploads/2020/05/shutterstock_1710468256.jpg",
            "https://respostas.sebrae.com.br/wp-content/uploads/2020/06/como_fazer_hamburguer_caseiro-806x440.jpg",
            "https://conteudo.imguol.com.br/c/entretenimento/71/2020/05/27/guia-do-hamburguer---sanduiche-1590607899872_v2_1920x1231.jpg",
            "https://www.selecoes.com.br/wp-content/uploads/2019/05/hamburguer-760x450.jpg",
        ],
    },
    {
        id: '12j3123',
        key: 1,
        name: 'Hot Roll',
        description: "O hot roll (ou simplesmente hot) ou sushi empanado é um alimento abrasileirado da culinária japonesa, do tipo maki (\"sushi enrolado\"), feito com peixe, normalmente salmão ou atum, enrolados em uma alga marinha desidratada com arroz. Após fatiados em pedaços circulares, são cobertos por uma massa de farinha de trigo e fritos, sendo servidos empanados com um acompanhamento de molho (tarê ou shoyu).",
        price: 'R$ 12,99',
        category: 'Japanese',
        thumb:
            'https://imperialsushi.com.br/wp-content/uploads/2020/05/ROLL_HOTPHILADELPHIACROC.png',
        img: [
            'https://www.seekpng.com/png/full/265-2656789_hot-philadelphia-png-hot-roll-sushi-png.png',
            'https://pngimage.net/wp-content/uploads/2018/06/hot-philadelphia-png-6.png',
            'https://lh3.googleusercontent.com/proxy/MSssMLLk6RKMfQ8jMNJUPyiunkzdNoscAoJ6fJDLo7krb--mmhMkdZhphu0VXmgxApaKT8qBlHtFqA_I2c7MY7pTXc64utvQyazxRdHepUDdjvg7TmE9',
            'https://www.cozinhandopara2ou1.com/wp-content/uploads/2015/03/hotroll_cozinhandopara2ou1.jpg',
        ],
    },
    {
        id: '12j3123',
        key: 2,
        name: 'Yakisoba',
        description: "No Japão, o termo yakisoba (yaki = assar, grelhar; soba = macarrão) refere-se a um prato feito de macarrão refogado com legumes e carnes, temperado com um molho específico, muito parecido com o molho inglês. Apesar de sua origem chinesa, o yakisoba adaptou-se à culinária japonesa, constituindo um prato extremamente popular.",
        price: 'R$ 19,90',
        category: 'Japanese',
        thumb:
            'https://www.ikesushi.com.br/_imagens/culinaria-chinesa/yakisoba-tradicional.png',
        img: [
            'https://m.bonde.com.br/img/bondenews/2017/02/img_1_33_3222.jpg',
            'https://s2.glbimg.com/ws8Y42x-bKqwWsZ-aj2PbPPMz1A=/0x0:1280x853/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2020/z/v/wwKjd9SrOu2XF7EVb7Zw/yakisoba.jpeg',
            'https://img.cybercook.com.br/receitas/155/yakisoba-623x350.jpeg',
            'https://cozinhasimples.com.br/wp-content/uploads/2016/04/yakisoba-cozinha-simples.jpg',
        ],
    },
    {
        id: '12j3123',
        key: 3,
        name: 'Temaki',
        description: "",
        price: 'R$ 14,99',
        category: 'Japanese',
        thumb:
            'https://lh3.googleusercontent.com/proxy/bgw4h6XlOIbYOQ4UJOPD15qsEA5-apk6sRQAPdCQsjAaU80IKST1GcpPfXMSYOXE8wL6CN6FrytGnnmx3U3Hbs8o29p5BMS4st5GwztQMhbxuqJyR0TH34x3s70iVhg6fR42cDenTf29j4lNoL6XIvgz',
        img: [
            'https://lh3.googleusercontent.com/proxy/D8B-cGDZETBCpbDFxNMmy65iivjo5yEe327SKiXCUKFzv1IAUBMZK1Cfu-1eIJL_cx7lStOjzMBlMYJg_VW5bG0b7NpZKs49ba_D6sVbWc4lCt5EGBtMrGFA9Jgs4jfbhmMqIEgIH4CPMD7ywsUoyAnhKyT_u3z9ISYbpZsF_FbqE00',
            'https://media.gazetadopovo.com.br/bomgourmet/2014/08/tn_620_600_temaki_141113-24cf8d90.jpg',
            'https://i2.wp.com/mundo-nipo.com/wp-content/uploads/2015/06/Temaki-Foto-JustOnecookbook-900x900-14-05-2016.jpg?fit=810%2C810&ssl=1',
        ],
    },
    {
        id: '12j3123',
        key: 4,
        name: 'Sushi',
        description: "",
        price: 'R$ 13,99',
        category: 'Japanese',
        thumb: 'https://www.transparentpng.com/thumb/sushi/zcfCRy-sushi-vector.png',
        img: [],
    },
    {
        id: '12j3123',
        key: 5,
        name: 'Hamburguer',
        description: "",
        price: 'R$ 10,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
        ],
    },
    {
        id: '12j3123',
        key: 6,
        name: 'Hamburguer',
        description: "",
        price: 'R$ 10,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
        ],
    },
    {
        id: '12j3123',
        key: 7,
        name: 'Hamburguer',
        description: "",
        price: 'R$ 10,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
        ],
    },
    {
        id: '12j3123',
        key: 8,
        name: 'Hamburguer',
        description: "",
        price: 'R$ 10,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
        ],
    },
    {
        id: '12j3123',
        key: 9,
        name: 'Hamburguer',
        description: "",
        price: 'R$ 10,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
        ],
    },
    {
        id: '12j3123',
        key: 10,
        name: 'Hamburguer',
        description: "",
        price: 'R$ 10,00',
        category: 'Fast Food',
        thumb: 'https://assets.stickpng.com/images/5882488ae81acb96424ffaaf.png',
        img: [
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
            'https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.com.br/files/BigKing_detail.png',
        ],
    },
];